spring.application.name=Sistema-Donacion-Sangre
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/donacionsangre_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.messages.basename=messages
spring.messages.encoding=UTF-8
logging.level.co.sena.cimm.adso=DEBUG
logging.level.org.hibernate.SQL=DEBUG
jwt.secret=cimm_adso_sena_blood_bank_secret_key_2024
jwt.expiration=86400000
